version: '3.9'

services:
  nginx:
    image: 'nginx:1.25.3'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/dev.conf:/etc/nginx/sites-enabled/dev.conf
      - ./www:/var/www
    ports:
      - 3113:80
    links:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./www:/var/www
