version: '3.9'

services:
  nginx:
    image: 'nginx:1.25.3'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/dev.conf:/etc/nginx/sites-enabled/dev.conf
      - ./www:/var/www
    ports:
      - 3113:80
    links:
      - php
    healthcheck:
      test: curl -sS http://nginx | grep -c works > /dev/null
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 5s

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./www:/var/www
